# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import daemon_pb2 as daemon__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in daemon_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkspaceDaemonStub:
    """Workspace Daemon API.
    All filesystem paths are interpreted relative to the daemon's configured
    workspace root. Paths that escape the workspace root are rejected.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadFile = channel.unary_unary(
                '/tc.daemon.v1.WorkspaceDaemon/ReadFile',
                request_serializer=daemon__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=daemon__pb2.ReadFileResponse.FromString,
                _registered_method=True)
        self.WriteFile = channel.unary_unary(
                '/tc.daemon.v1.WorkspaceDaemon/WriteFile',
                request_serializer=daemon__pb2.WriteFileRequest.SerializeToString,
                response_deserializer=daemon__pb2.WriteFileResponse.FromString,
                _registered_method=True)
        self.ExecCommand = channel.unary_unary(
                '/tc.daemon.v1.WorkspaceDaemon/ExecCommand',
                request_serializer=daemon__pb2.ExecCommandRequest.SerializeToString,
                response_deserializer=daemon__pb2.ExecCommandResponse.FromString,
                _registered_method=True)
        self.GitCreateBranch = channel.unary_unary(
                '/tc.daemon.v1.WorkspaceDaemon/GitCreateBranch',
                request_serializer=daemon__pb2.GitCreateBranchRequest.SerializeToString,
                response_deserializer=daemon__pb2.GitCreateBranchResponse.FromString,
                _registered_method=True)
        self.GitStatus = channel.unary_unary(
                '/tc.daemon.v1.WorkspaceDaemon/GitStatus',
                request_serializer=daemon__pb2.GitStatusRequest.SerializeToString,
                response_deserializer=daemon__pb2.GitStatusResponse.FromString,
                _registered_method=True)
        self.GitCommit = channel.unary_unary(
                '/tc.daemon.v1.WorkspaceDaemon/GitCommit',
                request_serializer=daemon__pb2.GitCommitRequest.SerializeToString,
                response_deserializer=daemon__pb2.GitCommitResponse.FromString,
                _registered_method=True)


class WorkspaceDaemonServicer:
    """Workspace Daemon API.
    All filesystem paths are interpreted relative to the daemon's configured
    workspace root. Paths that escape the workspace root are rejected.
    """

    def ReadFile(self, request, context):
        """Read a file (optionally a bounded chunk) from the workspace root.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFile(self, request, context):
        """Atomically write a file using compare-and-set on the current SHA-256.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecCommand(self, request, context):
        """Execute a command inside the workspace sandbox with an explicit timeout.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GitCreateBranch(self, request, context):
        """Create a git branch for TC changes (fails if it would clobber work).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GitStatus(self, request, context):
        """Report the git status of the workspace.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GitCommit(self, request, context):
        """Commit staged/specified changes safely.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkspaceDaemonServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=daemon__pb2.ReadFileRequest.FromString,
                    response_serializer=daemon__pb2.ReadFileResponse.SerializeToString,
            ),
            'WriteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=daemon__pb2.WriteFileRequest.FromString,
                    response_serializer=daemon__pb2.WriteFileResponse.SerializeToString,
            ),
            'ExecCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecCommand,
                    request_deserializer=daemon__pb2.ExecCommandRequest.FromString,
                    response_serializer=daemon__pb2.ExecCommandResponse.SerializeToString,
            ),
            'GitCreateBranch': grpc.unary_unary_rpc_method_handler(
                    servicer.GitCreateBranch,
                    request_deserializer=daemon__pb2.GitCreateBranchRequest.FromString,
                    response_serializer=daemon__pb2.GitCreateBranchResponse.SerializeToString,
            ),
            'GitStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GitStatus,
                    request_deserializer=daemon__pb2.GitStatusRequest.FromString,
                    response_serializer=daemon__pb2.GitStatusResponse.SerializeToString,
            ),
            'GitCommit': grpc.unary_unary_rpc_method_handler(
                    servicer.GitCommit,
                    request_deserializer=daemon__pb2.GitCommitRequest.FromString,
                    response_serializer=daemon__pb2.GitCommitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tc.daemon.v1.WorkspaceDaemon', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tc.daemon.v1.WorkspaceDaemon', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkspaceDaemon:
    """Workspace Daemon API.
    All filesystem paths are interpreted relative to the daemon's configured
    workspace root. Paths that escape the workspace root are rejected.
    """

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tc.daemon.v1.WorkspaceDaemon/ReadFile',
            daemon__pb2.ReadFileRequest.SerializeToString,
            daemon__pb2.ReadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tc.daemon.v1.WorkspaceDaemon/WriteFile',
            daemon__pb2.WriteFileRequest.SerializeToString,
            daemon__pb2.WriteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tc.daemon.v1.WorkspaceDaemon/ExecCommand',
            daemon__pb2.ExecCommandRequest.SerializeToString,
            daemon__pb2.ExecCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GitCreateBranch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tc.daemon.v1.WorkspaceDaemon/GitCreateBranch',
            daemon__pb2.GitCreateBranchRequest.SerializeToString,
            daemon__pb2.GitCreateBranchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GitStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tc.daemon.v1.WorkspaceDaemon/GitStatus',
            daemon__pb2.GitStatusRequest.SerializeToString,
            daemon__pb2.GitStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GitCommit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tc.daemon.v1.WorkspaceDaemon/GitCommit',
            daemon__pb2.GitCommitRequest.SerializeToString,
            daemon__pb2.GitCommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
